# Generated by Django 3.0 on 2019-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='belgian_championship',
            field=models.BooleanField(default=False),
        ),
    ]
