# Generated by Django 2.2.4 on 2019-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='created',
            new_name='founded',
        ),
        migrations.AddField(
            model_name='team',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
