# Generated by Django 2.2.3 on 2019-08-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rating',
        ),
    ]
