# Generated by Django 3.0.5 on 2020-04-05 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='website.Category'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='teams',
            field=models.ManyToManyField(related_name='_pool_teams_+', to='website.Club'),
        ),
    ]
