# Generated by Django 2.2.dev20181213125159 on 2018-12-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_competition_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='level',
            new_name='rating',
        ),
    ]
