# Generated by Django 3.1.1 on 2020-09-19 11:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200405_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbmember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(help_text='Do not create pools for a league type competition', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(help_text='Full post body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A few lines describing what the post is about', null=True),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dob', models.DateField()),
                ('media_consent', models.BooleanField(default=False)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.club')),
            ],
        ),
    ]
