# Generated by Django 3.0 on 2019-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_competition_belgian_championship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='belgian_championship',
            field=models.BooleanField(default=False, verbose_name='belgian national championship ?'),
        ),
        migrations.AlterField(
            model_name='match',
            name='invitational_match',
            field=models.BooleanField(default=False, verbose_name='invitational match ?'),
        ),
    ]
