# Generated by Django 2.2.7 on 2019-12-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191201_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(blank=True, choices=[('PS', 'Pool match'), ('PO', 'Playoff'), ('QF', 'Quarter final'), ('SF', 'Semi final'), ('FF', 'Final')], max_length=2),
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Bonus points can be negative')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Team')),
            ],
        ),
    ]
