# Generated by Django 2.2.4 on 2019-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190913_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
