# Generated by Django 2.2.5 on 2019-10-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbmember',
            old_name='board_member',
            new_name='committee_member',
        ),
        migrations.RenameField(
            model_name='tbmember',
            old_name='board_position',
            new_name='committee_position',
        ),
        migrations.RenameField(
            model_name='tbmember',
            old_name='more',
            new_name='referee_text',
        ),
        migrations.AddField(
            model_name='tbmember',
            name='committee_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
