# Generated by Django 2.2.5 on 2019-09-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190915_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='long',
            new_name='lng',
        ),
    ]
