# Generated by Django 2.2.6 on 2019-10-18 17:04

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191017_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', filebrowser.fields.FileBrowseField(max_length=500)),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Tag')),
            ],
        ),
    ]
