# Generated by Django 2.2.7 on 2019-12-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191202_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='away_bonus',
        ),
        migrations.RemoveField(
            model_name='match',
            name='home_bonus',
        ),
    ]
