# Generated by Django 3.0 on 2019-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191206_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('PR', 'Two stages: pools and rank'), ('PP', 'Two stages: pools and playoff matches'), ('LL', 'Point based system')], default='LL', max_length=2),
            preserve_default=False,
        ),
    ]
