# Generated by Django 2.2.6 on 2019-11-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_bannerpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Competition')),
            ],
            bases=('website.competition',),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('competition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Competition')),
            ],
            bases=('website.competition',),
        ),
        migrations.RemoveField(
            model_name='match',
            name='competition',
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Match')),
                ('match_type', models.CharField(choices=[('PS', 'Pool match'), ('PO', 'Playoff'), ('QF', 'Quarter final'), ('SF', 'Semi final'), ('FF', 'Final')], default='PS', max_length=2)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Tournament')),
            ],
            bases=('website.match',),
        ),
        migrations.CreateModel(
            name='LeagueMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.Match')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.League')),
            ],
            bases=('website.match',),
        ),
    ]
