# Generated by Django 2.1.1 on 2018-12-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
