# Generated by Django 2.2.5 on 2019-09-15 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190915_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbmember',
            name='coach',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbmember',
            name='coach_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='tbmember',
            name='coach_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbmember',
            name='referee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbmember',
            name='referee_board_member',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
