# Generated by Django 2.2.8 on 2019-12-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20191202_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name_plural': 'Bonuses'},
        ),
    ]
