# Generated by Django 3.0 on 2019-12-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_competition_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('MO', 'MO'), ('WO', 'WO'), ('XO', 'XO'), ('M27', 'M27'), ('W27', 'W27'), ('X27', 'X27'), ('M30', 'M30'), ('W30', 'W30'), ('X30', 'X30'), ('M30', 'M40'), ('W30', 'W40'), ('X40', 'X40'), ('JO', 'JO')], help_text='Men open, women open, mixed open...', max_length=3),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('PR', 'Two stages: pools and rank'), ('PP', 'Two stages: pools and playoff matches'), ('LL', 'League: point based system')], max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(blank=True, choices=[('PS', 'Pool match'), ('RS', 'Ranking match'), ('PO', 'Playoff'), ('QF', 'Quarter final'), ('SF', 'Semi final'), ('FF', 'Final')], help_text='Leave blank for league style competitions', max_length=2),
        ),
    ]
