# Generated by Django 3.1.1 on 2020-09-21 19:33

from django.db import migrations


def copy_clubs(apps, schema_editor):
    Club = apps.get_model("website", "Club")
    BelgianClub = apps.get_model("website", "BelgianClub")
    TBMember = apps.get_model("website", "TBMember")
    Match = apps.get_model("website", "Match")
    Bonus = apps.get_model("website", "Bonus")

    for club in Club.objects.all():
        if club.main_belgian_club:
            bc = BelgianClub.objects.create(
                name=club.name,
                logo=club.logo,
                founded=club.founded,
                website=club.website,
                facebook=club.facebook,
                instagram=club.instagram,
                venue=club.venue,
                lat=club.lat,
                lng=club.lng,
                member_club=club.member_club
            )
            bc.save()

            for member in TBMember.objects.filter(club=club):
                member.club = bc
                member.save()
            for match in Match.objects.filter(away_team=club):
                match.away_team = bc
                match.save()
            for match in Match.objects.filter(home_team=club):
                match.home_team = bc
                match.save()
            for bonus in Bonus.objects.filter(team=club):
                bonus.team = bc
                bonus.save()

            club.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_belgianclub'),
    ]

    operations = [
        migrations.RunPython(copy_clubs)
    ]
