# Generated by Django 2.1.5 on 2019-01-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-when'], 'verbose_name_plural': 'matches'},
        ),
    ]
