# Generated by Django 3.0 on 2019-12-09 18:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191206_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.Competition'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='tie_value',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='win_value',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='website.Category'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='website.Category'),
        ),
        migrations.AlterField(
            model_name='tbmember',
            name='coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbmember',
            name='committee_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbmember',
            name='referee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tbmember',
            name='referee_board_member',
            field=models.BooleanField(default=False),
        ),
    ]
