# Generated by Django 2.2.6 on 2019-11-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191130_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguematch',
            options={'verbose_name_plural': 'League matches'},
        ),
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'verbose_name_plural': 'Tournament matches'},
        ),
    ]
