# Generated by Django 3.0 on 2019-12-09 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191209_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbmember',
            name='referee_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
