# Generated by Django 2.1.5 on 2019-01-31 11:31

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190130_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='refs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=filebrowser.fields.FileBrowseField(default='base/team_placeholder.png', max_length=500),
        ),
    ]
