# Generated by Django 2.2.6 on 2019-11-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191130_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='address',
        ),
        migrations.AddField(
            model_name='team',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.Venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
