# Generated by Django 3.1.1 on 2020-09-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200921_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='team',
            new_name='club',
        ),
        migrations.RemoveField(
            model_name='club',
            name='main_belgian_club',
        ),
        migrations.RemoveField(
            model_name='club',
            name='member_club',
        ),
        migrations.AddField(
            model_name='belgianclub',
            name='member_club',
            field=models.BooleanField(default=False, verbose_name='Touch Belgium registered ?'),
        ),
    ]
