# Generated by Django 2.2.5 on 2019-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbmember',
            name='more',
            field=models.TextField(blank=True, null=True),
        ),
    ]
