# Generated by Django 3.1.2 on 2020-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200921_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='token',
            field=models.CharField(default='c61978', max_length=6),
        ),
    ]
