# Generated by Django 3.0 on 2019-12-10 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191209_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tbmember',
            options={'ordering': ['name'], 'verbose_name': 'Touch Belgium member', 'verbose_name_plural': 'Touch Belgium members'},
        ),
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
