# Generated by Django 2.1.5 on 2019-01-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190131_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
