# Generated by Django 3.0 on 2019-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191210_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='social',
            field=models.BooleanField(default=False, verbose_name='social ?'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(),
        ),
    ]
