# Generated by Django 2.1.5 on 2019-01-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190131_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_bonus',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
