# Generated by Django 3.1.2 on 2020-10-04 11:41

import uuid
from django.db import migrations


def gen_tokens(apps, schema_editor):
    Club = apps.get_model("website", "Club")

    for club in Club.objects.all():
        club.token = uuid.uuid4().hex[0:6]
        club.save()


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_club_token'),
    ]

    operations = [
        migrations.RunPython(gen_tokens)
    ]
