# Generated by Django 3.0 on 2019-12-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20191210_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-end_date']},
        ),
    ]
