# Generated by Django 3.1.2 on 2020-10-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20201004_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbmember',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True),
        )
    ]
