# Generated by Django 3.0 on 2019-12-11 15:02

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20191210_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
