# Generated by Django 3.0.2 on 2020-01-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20191211_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='forfeit',
            field=models.BooleanField(default=False, verbose_name='forfeit ?'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
