# Generated by Django 3.1.2 on 2020-10-14 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20201004_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.belgianclub'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time the registration was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time in which it was reviewed by the club rep / director', null=True),
        ),
        migrations.AlterField(
            model_name='tbmember',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.belgianclub'),
        ),
    ]
