# Generated by Django 3.0.2 on 2020-01-19 23:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_competition_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['word']},
        ),
        migrations.AddField(
            model_name='competition',
            name='short_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
