# Generated by Django 3.0.2 on 2020-01-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerpicture',
            options={'ordering': ['tag', 'id']},
        ),
        migrations.AlterField(
            model_name='competition',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
