# Generated by Django 3.0.2 on 2020-01-25 00:37

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200125_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', filebrowser.fields.FileBrowseField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ManyToManyField(to='website.Picture')),
            ],
            options={
                'verbose_name_plural': 'galleries',
            },
        ),
    ]
