# Generated by Django 3.0.2 on 2020-01-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_gallery_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='picture',
            new_name='pictures',
        ),
        migrations.AddField(
            model_name='picture',
            name='in_gallery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.Gallery'),
            preserve_default=False,
        ),
    ]
