# Generated by Django 3.0.2 on 2020-01-25 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200125_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='pictures',
        ),
    ]
