# Generated by Django 3.0.2 on 2020-01-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_gallery_pictures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='url',
        ),
    ]
