# Generated by Django 3.0.2 on 2020-01-25 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20200125_0156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='url',
            new_name='picture',
        ),
    ]
